### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by ishanSrt** [mark-vandenberg/g-hub-mouse-gestures#2]
I am using the mouse logitech g502 lightspeed wireless
does the ghub software need to be closed for the proper function of this script?
installed lua with brew
and then ran your script with command `lua MouseGestures.lua`
nothing really works
tried fiddling around with giving different values to `gestureButtonNumber` and `navigationButtonNumber`
still nothing works

**Comment by mark-vandenberg** [comment]
Have you read the installation instructions in the README.md file? You copy past the code in a script file in the g-hub software, you shouldn't need to install lua manually it comes with g-hub

**Comment by ishanSrt** [comment]
closing this issue since this is resolved and was indeed a problem with following readme
