### ISSUE TITLE
how to write these gestures to the mouse's on board memory

### ISSUE THREAD

**Issue by ishanSrt** [mark-vandenberg/g-hub-mouse-gestures#4]
There is a delay whenever you are not using onboard memory and whenever you wake the computer/mouse up and the gestures do take some time to load or switch back to the profile memory to get them to start working. Is this functionality available?

**Comment by mark-vandenberg** [comment]
This sounds like a G-hub thing that is loading the script after loading the rest of the profile or something. Not sure though. At this point I don't have a clue if and how I could solve this. The script is running in g-hub and I haven't put a delay in the script or something to make it load slow.

**Comment by ishanSrt** [comment]
also worth mentioning that the gestures don't work when using on board device memory mode. would snoop around if there is a way to write the script to the device memory too.

**Comment by mark-vandenberg** [comment]
I haven't played around with on board memory (not even sure if my mouse supports it). From my current (limited) understanding the script runs in the g-hub app. If onboard memory mode can run without g-hub I can see why the script wouldn't work.
