### ISSUE TITLE
can we add the functionality of detecting while the gesture button is pressed and we change our gesture direction

### ISSUE THREAD

**Issue by ishanSrt** [mark-vandenberg/g-hub-mouse-gestures#5]
I'd like the mission control to be navigable while the button is pressed (just like the gestures work for MX master). seems like it can be done by throwing the event in a loop until mouse button is released and then calculating gestures using relative position

**Comment by ishanSrt** [comment]
I'm happy to make a PR for this, unless you want this for yourself 😉

**Comment by mark-vandenberg** [comment]
I don't have an MX mouse, and I am not really sure how the functionality is supposed to work. You could make a PR. And I'll check if it fits the simplicity of this script as it is. If I don't think it fits you could fork this repo and add it yourself.

**Comment by mark-vandenberg** [comment]
I don't see this working with how the script is currently set up
