### ISSUE TITLE
False diagonal detections

### ISSUE THREAD

**Issue by h13Bishop** [mark-vandenberg/g-hub-mouse-gestures#6]
Hello.

Do you still use this and it works well?

Just tried to use your script but 80% of the time it works poorly.
It works as intended only if I move the mouse strictly horizontally or vertically.
If I move the mouse slightly diagonally then I get two actions at once, movedUP and movedRight if I move the mouse up and a bit to the right.

What I'm imagining, that script must catch only the movement in the blue zones for corresponding movement direction and ignore movement in gray zones.
![example](https://github.com/user-attachments/assets/54ee237e-6902-42b1-9b18-8abe46e75eaf)

But I don't understand the logic of the movement detection part of the script.
Could someone help with this issue? Thank you.

**Comment by mark-vandenberg** [comment]
Hi, 

I don't use it that often anymore personally but it should work still. 

It was intend for use where you  mostly move your mouse in 1 direction when holding a button to get the disered action like the MX-Master mouse software. The way the "gesture detection" works is based on a couple things. 

On lines 32-34 we have the minimal movement values. With those values you can set like a "deadzone". If your mouse doesn't move more than that, it won't perform an action.  

The second part of the detection happens at lines 79-87. There we calculate the  actual movement of the mouse and determine that if that is above the minimal value it can perform a gesture. 

The current logic doesn't check if multiple gestures will perform simultaniously. 

![WhatsApp Image 2024-08-21 at 16 16 19_a7cdc120](https://github.com/user-attachments/assets/ac8a86bc-4d08-437f-bb10-838bdd7f7e68)

If you in general move your mouse in one direction and slightly in the second direction, and it still detects two gestures the easy solution for you now is increase(and tweak) the minimal values described above. This increases how far you would need to move your mouse for it detect an action in one direction but also the "wiggle room" in the second direction. 

I hope this helps. If it is not enough I could look into a way to make the detection a bit more sofisticated/robust. I do have to say the current way is pretty lazy but keeps it understandable. And it worked for me (and quiet some other folks apparently) so never looked into blocking the diagnals.

**Comment by h13Bishop** [comment]
Thank you for the clarification! I'll try to take a closer look at the code to understand it myself, so maybe I could modify it to my needs.
